apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sample-app
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/gci-techss-gcp-pjnp-01nl165115/sample-repo/sample-app